const breederActionTypes = {
    BREEDER_TOGGLE_DRAWER: 'BREEDER_TOGGLE_DRAWER',
    BREEDER_CHANGE_MOTHER: 'BREEDER_CHANGE_MOTHER',
    BREEDER_CHANGE_FATHER: 'BREEDER_CHANGE_FATHER',
    BREEDER_SWAP_PEPES: 'BREEDER_SWAP_PEPES'
};

export default breederActionTypes;
