const web3AT = {
    ASK_WEB3_ON: 'ASK_WEB3_ON',
    WEB3_CONNECT_STATUS: 'WEB3_CONNECT_STATUS',
    WEB3_NETID: 'WEB3_NETID',
    WEB3_NETID_START_POLL: 'WEB3_NETID_START_POLL',
    WEB3_NETID_STOP_POLL: 'WEB3_NETID_STOP_POLL'
};

export default web3AT;
